# Generated by Django 4.0 on 2023-04-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descr', models.TextField(max_length=350)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
